### PR TITLE
finished effects

### PR DESCRIPTION
**Pull request by rdfriedl**
### Changes:
- finished all effects
- added constructors for each effect
- added "ParentEffect" class for effects like "Merge" & "ComponentTransfer"
- added "ChildEffect" class for child effects like "MergeNode" & "FuncR"

**Effect**
 - Constructor(*effect constructors arguments*, attrs)
  - *attrs* [ Object ] a key value pair for attributes

**ParentEffect**
 - Constructor(*effect constructors arguments*, attrs, children)
  - *attrs* [ Object ] a key value pair for attributes
  - *children* [ Array ] a array of ChildEffects or SVG.Elements

**ChildEffect**
 - Constructor(*effect constructors arguments*, attrs)
  - *attrs* [ Object ] a key value pair for attributes

the "attrs" & "children" arguments dont get in the way of the constructors arguments, for example its now possible to do this

```javascript
image.filter(function(add){
    add.gaussianBlur(30,6,{
        result: "out"
    })
})
```
or
```javascript
image.filter(function(add){
    add.gaussianBlur({
        stdDeviation: "30 6",
        result: "out"
    })
})
```

this is possible because when the constructor is called it finds and removes the "attrs" then calls the effects constructor without the "attrs" argument

#### Merge
- Constructor(*effects to merge*)
- in(effect)
 - effect SVG.Effect creates a SVG.MergeNode with its "in" set the the .result() of the "effect" and appends it to its self

Example

```javascript
image.filter(function(add){
    add.gaussianBlur(30,0).merge(add.source)
})
```
or
```javascript
image.filter(function(add){
    add.gaussianBlur(30,0,{
        result: "blur"
    })
    add.merge("blur",add.source,{
        result: "mergeOut"
    })
})
```

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Sorry - I forgot about this.
First of all thank you for putting so much effort into this!
I have a few questions I like to ask:

- is this code svg.js v2 ready?
- does it change the old api of the pluginß
- where are there `attr` params in the constructor? Isnt that something you should apply after constructing the filter and not in the constructor itself?

Oh - it would be great if you could include the doc changes in this PR, too :)

**Comment by rdfriedl** [comment]
i dont mind working on this library at all, its my go-to library when it comes to svg :D

-  iv been using it a lot with the latest version of svg so i "think" its compatible (further testing my be required)
- nope, aside from the attr thing
- its at the end of the constructor, i cant say im very happy with it since the effects have a .attr() function anyway.

i cant remember y i added the attr object to the end of the constructor when i could have just done
```javascript
new constructor().attr(attrs)
```

though the `children` argument is helpful on the ParentEffects constructor like `merge`
it allows you to do
```javascript
new SVG.MergeEffect([
     new SVG.MergeNode('someid'),
     new SVG.MergeNode('SourceGraphic')
])
```

though again i dont know y you could not do
```javascript
var merge = new SVG.MergeEffect();
merge.add(new SVG.MergeNode('someid'));
merge.add(new SVG.MergeNode('SourceGraphic'));
```

i guess what im getting at is i dont know y i added them.
if you want i can remove them, it might help to simplify the code.

**Comment by Fuzzyma** [comment]
For testing purposes there is a spec-folder in which you can open the index in chrome.
When nothing got broken duo your changes or svg.js v2 everything should be green. Well - wout often did not check only the public api so it might that a few things will be red anyway.
Also you can add the new stuff to the tests in the `/spec/spec/svg.filter.js` file.

I am always a fan of simple code so if there is no other important reason about keeping the attr-param I would remove it.
I am not sure about the children argument which looks pretty useful to me.
I am not aware of all the filter stuff in svg. Does the mergeEffect exists as element in svg? Or is it a construct like SVG.Set? In the first case it would be more like a group.
I think I will implement such a children element in groups, too - so keeping this here is ok I guess :).

**Comment by rdfriedl** [comment]
i opened the tests and they blew up
i think it was because it could not find the svg.js library, so i made it get svg.min.js from cdnjs.
and everything worked fine :)

the MergeEffect is a svg element kinda like a group, it holds MergeNode(s).

the way the children array works is when you call the constructor tests to see if there is a array in the last argument, if so it removes the array from the arguments and then calls the elements class constructor without the array.
then once it has the new element, it adds all the children from the array.

the reason i think this is something that should not be kept is because:
1: your passing a argument to the constructor that is not really part of the elements constructor, but instead is cut off my a function that intercepts the call.
2: this could proove to be a problem on element constructors that require a array, because the intercept function might cut off the array and then the original element constructor would not get the array.

what i would suggest is that we make it so that the class constructor for things like Group(s) and MergeEffect(s) would take arrays
for example
``` javascript
MergeEffect = funciton(children){
    //the original code in the constructor would go here

    //then we would add something like this to add all the children
    for(var i in children){
        if(children[i] instanceof SVG.Element) this.add(children[i]);
    }
}
````

that way it would be up to the class specific constructor to add its children and we would not have to deal with a function that intercepts the call and adds the children.

i used the bindConstructor so that i could call a constructor with an arguments array, instead of having to pass every argument in.

i wanted to so something like this, where it would pas the arugments array into the constructor.
```javascript
function offset(){
     return this.put(new SVG.OffsetEffect.apply(undefined,arguments));
}
```

but as you know running that throws an error.
i did a quick search and found a better way
```javascript
function offset(){
    //what i used
    return this.put(new (bindConstructor(SVG.OffsetEffect,arguments)));

    //this would make more sense and we would not need the "bindConstructor" function
    return this.put(new (SVG.OffsetEffect.bind.apply(SVG.OffsetEffect,[undefined,'testing'])));
}
```

so ill remove that function to simplify things a bit.

its been a while since i wrote this code, and i have learned a lot since then, so im finding my self looking back on this code and thinking "why did i do that", and "thats not a good idea..."
so i think ill run over it and fix a few things up :D

ps. seems like every time i reply to these messages they keep getting longer :p

**Comment by Fuzzyma** [comment]
The structure you chose for the constructor is the one I imagined.
Seems like I didnt read the code properly there.

However I just realized, that the first svg-filters where written when the code of the library was very young. Please take a look at the `SVG.invent` method which simplyfies the whole inheritance thing and makes stuff like `return this.put(new (SVG.OffsetEffect.bind.apply(SVG.OffsetEffect,[undefined,'testing'])));` even cleaner e.g. `return this.put(new SVG.OffsetEffect('testing'));`

Note that I am still not aware about how filters work in SVG. So this are just my 50 cents

**Comment by rdfriedl** [comment]
hmm that would be a lot more readable.
i like the `SVG.invent` syntax.
though unfortunately this plugin is not written with that syntax.

im going to fix the code i have right now, that includes:
1: removing the `attr` argument from all the effect constructors
2: remove the `children` argument from all the parentEffect constructors, and make it an argument on the specific effects constructor.
3: ill also remove the `bindConstructor` function to simplify things

after that we could look into making every effect use the `SVG.invent` syntax.

**Comment by Fuzzyma** [comment]
Sounds great! Just ask if you are unsure about things :)

**Comment by rdfriedl** [comment]
ok that should be it.

- i made all the classes use the SVG.invent function
- added some tests
- updated test libary
- removed the `attr` & `children` arguments from the constructors

on the MergeEffect you can still do:
```javascript
new SVG.MergeEffect([
    new SVG.MergeNode('some-id'),
    new SVG.MergeNode('SourceGraphic')
])
```
but now its handled by the `SVG.MergeEffects` constructor

also all the tests pass :D [tests](https://cdn.rawgit.com/rdfriedl/svg.filter.js/master/spec/index.html)

**Comment by Fuzzyma** [comment]
I know I can really be a pain in the ass but:
svg.js often can handle such arguments like in MergeEffects in different ways.
- array input
- multiple arguments instead
- Set of Elements (optional - I dont think that this is supported elsewhere so we can drop that)

You can easily add that on the follwoing way:
```javascript
function(children){
    if(!Array.isArray(children)){
        children = [].slice.call(arguments)
    }else if(children instanceof SVG.Set){
        children = children.valueOf()
    }

}
```

I think you know that anyway so only just in case :D

Feel free to also update the docs ;)

**Comment by rdfriedl** [comment]
ok should now be able to pass the inputs to a merge effect in three ways
```javascript
filter.merge("some-id",anotherEffect);
```

```javascript
filter.merge([
    "some-id",
    anotherEffect
])
```

```javascript
var set = new SVG.Set();
set.add(filter.flood('black'));
set.add(filter.offset(10));
filter.merge(set);
```

also whats wrong with semicolons in the specs?
isnt it always a good idea to put semicolons in your javascript.

ps. ill update the docs in a bit :D

**Comment by Fuzzyma** [comment]
Did you just replaced the node with id's? Because I think passing nodes is better than passing id's. Maybe I just didn't understand that correctly though... 

Anyway thanks again for your work!

**Comment by rdfriedl** [comment]
oh sorry i did not specify that.
all the effects have their `toString` methods set up so that they will return whats in their `result` attr.
so when a effect sets its `in` attr to another effect it will call the `toString` method and it will return the other effects `result`
thats how i found it so i did not change it.

**Comment by rdfriedl** [comment]
ok i wrote up all the docs on the effects along with links to their definition in the W3 Doc.
i think thats about it :D

**Comment by rdfriedl** [comment]
i think i finished everything i set out to add / fix
the docs have all the details about the effects and how to create them
i also added a section about how to chain effect

and one thing i forgot to mention in my commit messages.
i made the in() and result() methods act as getters / setters

also i added a lot more tests (because tests are awesome :D) you can see them [here](https://rawgit.com/rdfriedl/svg.filter.js/master/spec/index.html)

**Comment by Fuzzyma** [comment]
Great work! You are awesome! :D
Looks like its time to merge :)

**Comment by Fuzzyma** [comment]
The new version is published on npm and bower, too now. I had to publish it as version 2 because someone published the old version (which was 0.4) as version 1. But beside that: Everything great :)

**Comment by rdfriedl** [comment]
looks awesome, its nice to see this library finally finished :D
and dont hesitate to ask me to help with these libraries, i cant promise ill have time.
but i still find it fun to work on this stuff

also i work with this library all the time so i "almost" know it all

**Pull request merged**
